version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_POSTHOG_KEY: ${NEXT_PUBLIC_POSTHOG_KEY}
        NEXT_PUBLIC_POSTHOG_HOST: ${NEXT_PUBLIC_POSTHOG_HOST}
        DATABASE_URL: ${DATABASE_URL}
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: devnotify
      POSTGRES_PASSWORD: devnotifypassword
      POSTGRES_DB: devnotifydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devnotify -d devnotifydb"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
