version: "3.8"
services:
  postgres:
    image: postgres:16
    container_name: devnotify_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: devnotify
      POSTGRES_PASSWORD: devnotifypassword
      POSTGRES_DB: devnotifydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
