services:
  db-dev:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=devnotify
      - POSTGRES_PASSWORD=devnotifypassword
      - POSTGRES_DB=devnotifydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devnotify -d devnotifydb"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data_dev:
